export const ACADEMIC_HISTORY_SYMBOLS = {
    REPOSITORY: Symbol.for('ACADEMIC_HISTORY_REPOSITORY'),
    SERVICE: Symbol.for('ACADEMIC_HISTORY_SERVICE'),
    GET_USE_CASE: Symbol.for('GET_ACADEMIC_HISTORY_USE_CASE')
};
