export const ASSESSMENT_SYMBOLS = {
    REPOSITORY: Symbol.for('ASSESSMENT_REPOSITORY'),
    SERVICE: Symbol.for('ASSESSMENT_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_ASSESSMENT_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_ASSESSMENTS_USE_CASE'),
    UPDATE_USE_CASE: Symbol.for('UPDATE_ASSESSMENT_USE_CASE'),
    DELETE_USE_CASE: Symbol.for('DELETE_ASSESSMENT_USE_CASE')
};
