export const ATTENDANCE_SYMBOLS = {
    REPOSITORY: Symbol.for('ATTENDANCE_REPOSITORY'),
    SERVICE: Symbol.for('ATTENDANCE_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_ATTENDANCE_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_ATTENDANCE_USE_CASE'),
    UPDATE_USE_CASE: Symbol.for('UPDATE_ATTENDANCE_USE_CASE'),
    DELETE_USE_CASE: Symbol.for('DELETE_ATTENDANCE_USE_CASE')
};
