export const BEHAVIOR_REPORT_SYMBOLS = {
    REPOSITORY: Symbol.for('BEHAVIOR_REPORT_REPOSITORY'),
    SERVICE: Symbol.for('BEHAVIOR_REPORT_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_BEHAVIOR_REPORT_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_BEHAVIOR_REPORTS_USE_CASE'),
    UPDATE_USE_CASE: Symbol.for('UPDATE_BEHAVIOR_REPORT_USE_CASE'),
    DELETE_USE_CASE: Symbol.for('DELETE_BEHAVIOR_REPORT_USE_CASE')
};
