export const ENROLLMENT_SYMBOLS = {
    REPOSITORY: Symbol.for('ENROLLMENT_REPOSITORY'),
    SERVICE: Symbol.for('ENROLLMENT_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_ENROLLMENT_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_ENROLLMENTS_USE_CASE'),
    UPDATE_USE_CASE: Symbol.for('UPDATE_ENROLLMENT_USE_CASE'),
    DELETE_USE_CASE: Symbol.for('DELETE_ENROLLMENT_USE_CASE')
};
