export const MEETING_SYMBOLS = {
    REPOSITORY: Symbol.for('MEETING_REPOSITORY'),
    SERVICE: Symbol.for('MEETING_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_MEETING_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_MEETINGS_USE_CASE'),
    UPDATE_USE_CASE: Symbol.for('UPDATE_MEETING_USE_CASE'),
    DELETE_USE_CASE: Symbol.for('DELETE_MEETING_USE_CASE')
};
