export const PROMOTION_ACT_SYMBOLS = {
    REPOSITORY: Symbol.for('PROMOTION_ACT_REPOSITORY'),
    SERVICE: Symbol.for('PROMOTION_ACT_SERVICE'),
    CREATE_USE_CASE: Symbol.for('PROMOTION_ACT_CREATE_USE_CASE'),
    GET_USE_CASE: Symbol.for('PROMOTION_ACT_GET_USE_CASE'),
    LIST_USE_CASE: Symbol.for('PROMOTION_ACT_LIST_USE_CASE'),
    DELETE_USE_CASE: Symbol.for('PROMOTION_ACT_DELETE_USE_CASE')
};
