export const REPRESENTATIVE_SYMBOLS = {
    REPOSITORY: Symbol.for('REPRESENTATIVE_REPOSITORY'),
    SERVICE: Symbol.for('REPRESENTATIVE_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_REPRESENTATIVE_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_REPRESENTATIVES_USE_CASE'),
    GET_USE_CASE: Symbol.for('GET_REPRESENTATIVE_USE_CASE'),
    UPDATE_USE_CASE: Symbol.for('UPDATE_REPRESENTATIVE_USE_CASE'),
    DELETE_USE_CASE: Symbol.for('DELETE_REPRESENTATIVE_USE_CASE'),
};
