export const STUDENT_SYMBOLS = {
    REPOSITORY: Symbol.for('STUDENT_REPOSITORY'),
    SERVICE: Symbol.for('STUDENT_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_STUDENT_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_STUDENTS_USE_CASE'),
    GET_USE_CASE: Symbol.for('GET_STUDENT_USE_CASE'),
    UPDATE_USE_CASE: Symbol.for('UPDATE_STUDENT_USE_CASE'),
    DELETE_USE_CASE: Symbol.for('DELETE_STUDENT_USE_CASE')
};
