export const TEACHER_PLANNING_SYMBOLS = {
    REPOSITORY: Symbol.for('TEACHER_PLANNING_REPOSITORY'),
    SERVICE: Symbol.for('TEACHER_PLANNING_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_TEACHER_PLANNING_USE_CASE'),
    GET_USE_CASE: Symbol.for('GET_TEACHER_PLANNING_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_TEACHER_PLANNINGS_USE_CASE')
};
