export const TEACHER_ASSIGNMENT_SYMBOLS = {
    REPOSITORY: Symbol.for('TEACHER_ASSIGNMENT_REPOSITORY'),
    SERVICE: Symbol.for('TEACHER_ASSIGNMENT_SERVICE'),
    CREATE_USE_CASE: Symbol.for('CREATE_TEACHER_ASSIGNMENT_USE_CASE'),
    GET_USE_CASE: Symbol.for('GET_TEACHER_ASSIGNMENT_USE_CASE'),
    LIST_USE_CASE: Symbol.for('LIST_TEACHER_ASSIGNMENTS_USE_CASE')
};
