import { Container } from 'inversify';
import { TEACHER_SYMBOLS } from '../domain/symbols/Teacher';
import { TeacherRepositoryImpl } from '../infrastructure/api/TeacherRepositoryImpl';
import { TeacherService } from '../domain/services/TeacherService';
import { CreateTeacherUseCase } from '../application/usecases/teacher/CreateTeacherUseCase';
import { ListTeachersUseCase } from '../application/usecases/teacher/ListTeachersUseCase';
import { GetTeacherUseCase } from '../application/usecases/teacher/GetTeacherUseCase';
import { UpdateTeacherUseCase } from '../application/usecases/teacher/UpdateTeacherUseCase';
import { DeleteTeacherUseCase } from '../application/usecases/teacher/DeleteTeacherUseCase';
import { REPORT_CARD_SYMBOLS } from '../domain/symbols/ReportCard';
import { ReportCardRepositoryImpl } from '../infrastructure/api/ReportCardRepositoryImpl';
import { ReportCardService } from '../domain/services/ReportCardService';
import { GetReportCardUseCase } from '../application/usecases/report-card/GetReportCardUseCase';
import { OFFICIAL_RECORD_SYMBOLS } from '../domain/symbols/OfficialRecord';
import { OfficialRecordRepositoryImpl } from '../infrastructure/api/OfficialRecordRepositoryImpl';
import { OfficialRecordService } from '../domain/services/OfficialRecordService';
import { GetOfficialRecordUseCase } from '../application/usecases/official-record/GetOfficialRecordUseCase';
import { STATISTICS_SYMBOLS } from '../domain/symbols/Statistics';
import { StatisticsRepositoryImpl } from '../infrastructure/api/StatisticsRepositoryImpl';
import { StatisticsService } from '../domain/services/StatisticsService';
import { GetAttendanceStatisticsUseCase } from '../application/usecases/statistics/GetAttendanceStatisticsUseCase';
import { GetPerformanceStatisticsUseCase } from '../application/usecases/statistics/GetPerformanceStatisticsUseCase';
import { EXPORT_SYMBOLS } from '../domain/symbols/Export';
import { ExportRepositoryImpl } from '../infrastructure/api/ExportRepositoryImpl';
import { ExportService } from '../domain/services/ExportService';
import { ExportReportCardUseCase } from '../application/usecases/exports/ExportReportCardUseCase';
import { ExportStatisticsUseCase } from '../application/usecases/exports/ExportStatisticsUseCase';
import { PROMOTION_SYMBOLS } from '../domain/symbols/Promotion';
import { PromotionRepositoryImpl } from '../infrastructure/api/PromotionRepositoryImpl';
import { PromotionService } from '../domain/services/PromotionService';
import { PromoteStudentUseCase } from '../application/usecases/promotion/PromoteStudentUseCase';
import { PROMOTION_ACT_SYMBOLS } from '../domain/symbols/PromotionAct';
import { PromotionActRepositoryImpl } from '../infrastructure/api/PromotionActRepositoryImpl';
import { PromotionActService } from '../domain/services/PromotionActService';
import { CreatePromotionActUseCase } from '../application/usecases/promotion-act/CreatePromotionActUseCase';
import { GetPromotionActUseCase } from '../application/usecases/promotion-act/GetPromotionActUseCase';
import { ListPromotionActsUseCase } from '../application/usecases/promotion-act/ListPromotionActsUseCase';
import { DeletePromotionActUseCase } from '../application/usecases/promotion-act/DeletePromotionActUseCase';
import { TEACHER_ASSIGNMENT_SYMBOLS } from '../domain/symbols/TeacherAssignment';
import { TeacherAssignmentRepositoryImpl } from '../infrastructure/api/TeacherAssignmentRepositoryImpl';
import { TeacherAssignmentService } from '../domain/services/TeacherAssignmentService';
import { CreateTeacherAssignmentUseCase } from '../application/usecases/teacher-assignment/CreateTeacherAssignmentUseCase';
import { GetTeacherAssignmentUseCase } from '../application/usecases/teacher-assignment/GetTeacherAssignmentUseCase';
import { ListTeacherAssignmentsUseCase } from '../application/usecases/teacher-assignment/ListTeacherAssignmentsUseCase';
import { TEACHER_PLANNING_SYMBOLS } from '../domain/symbols/TeacherPlanning';
import { TeacherPlanningRepositoryImpl } from '../infrastructure/api/TeacherPlanningRepositoryImpl';
import { TeacherPlanningService } from '../domain/services/TeacherPlanningService';
import { CreateTeacherPlanningUseCase } from '../application/usecases/teacher-planning/CreateTeacherPlanningUseCase';
import { GetTeacherPlanningUseCase } from '../application/usecases/teacher-planning/GetTeacherPlanningUseCase';
import { ListTeacherPlanningsUseCase } from '../application/usecases/teacher-planning/ListTeacherPlanningsUseCase';
import { STUDENT_SYMBOLS } from '../domain/symbols/Student';
import { StudentRepositoryImpl } from '../infrastructure/api/StudentRepositoryImpl';
import { StudentService } from '../domain/services/StudentService';
import { CreateStudentUseCase } from '../application/usecases/student/CreateStudentUseCase';
import { ListStudentsUseCase } from '../application/usecases/student/ListStudentsUseCase';
import { GetStudentUseCase } from '../application/usecases/student/GetStudentUseCase';
import { UpdateStudentUseCase } from '../application/usecases/student/UpdateStudentUseCase';
import { DeleteStudentUseCase } from '../application/usecases/student/DeleteStudentUseCase';
import { REPRESENTATIVE_SYMBOLS } from '../domain/symbols/Representative';
import { RepresentativeRepositoryImpl } from '../infrastructure/api/RepresentativeRepositoryImpl';
import { RepresentativeService } from '../domain/services/RepresentativeService';
import { CreateRepresentativeUseCase } from '../application/usecases/representative/CreateRepresentativeUseCase';
import { ListRepresentativesUseCase } from '../application/usecases/representative/ListRepresentativesUseCase';
import { GetRepresentativeUseCase } from '../application/usecases/representative/GetRepresentativeUseCase';
import { UpdateRepresentativeUseCase } from '../application/usecases/representative/UpdateRepresentativeUseCase';
import { DeleteRepresentativeUseCase } from '../application/usecases/representative/DeleteRepresentativeUseCase';
import { ASSESSMENT_SYMBOLS } from '../domain/symbols/Assessment';
import { AssessmentRepositoryImpl } from '../infrastructure/api/AssessmentRepositoryImpl';
import { AssessmentService } from '../domain/services/AssessmentService';
import { CreateAssessmentUseCase } from '../application/usecases/assessment/CreateAssessmentUseCase';
import { ListAssessmentsUseCase } from '../application/usecases/assessment/ListAssessmentsUseCase';
import { UpdateAssessmentUseCase } from '../application/usecases/assessment/UpdateAssessmentUseCase';
import { DeleteAssessmentUseCase } from '../application/usecases/assessment/DeleteAssessmentUseCase';
import { ATTENDANCE_SYMBOLS } from '../domain/symbols/Attendance';
import { AttendanceRepositoryImpl } from '../infrastructure/api/AttendanceRepositoryImpl';
import { AttendanceService } from '../domain/services/AttendanceService';
import { CreateAttendanceUseCase } from '../application/usecases/attendance/CreateAttendanceUseCase';
import { ListAttendanceUseCase } from '../application/usecases/attendance/ListAttendanceUseCase';
import { UpdateAttendanceUseCase } from '../application/usecases/attendance/UpdateAttendanceUseCase';
import { DeleteAttendanceUseCase } from '../application/usecases/attendance/DeleteAttendanceUseCase';
import { BEHAVIOR_REPORT_SYMBOLS } from '../domain/symbols/BehaviorReport';
import { BehaviorReportRepositoryImpl } from '../infrastructure/api/BehaviorReportRepositoryImpl';
import { BehaviorReportService } from '../domain/services/BehaviorReportService';
import { CreateBehaviorReportUseCase } from '../application/usecases/behavior-report/CreateBehaviorReportUseCase';
import { ListBehaviorReportsUseCase } from '../application/usecases/behavior-report/ListBehaviorReportsUseCase';
import { UpdateBehaviorReportUseCase } from '../application/usecases/behavior-report/UpdateBehaviorReportUseCase';
import { DeleteBehaviorReportUseCase } from '../application/usecases/behavior-report/DeleteBehaviorReportUseCase';
import { MEETING_SYMBOLS } from '../domain/symbols/Meeting';
import { MeetingRepositoryImpl } from '../infrastructure/api/MeetingRepositoryImpl';
import { MeetingService } from '../domain/services/MeetingService';
import { CreateMeetingUseCase } from '../application/usecases/meeting/CreateMeetingUseCase';
import { ListMeetingsUseCase } from '../application/usecases/meeting/ListMeetingsUseCase';
import { UpdateMeetingUseCase } from '../application/usecases/meeting/UpdateMeetingUseCase';
import { DeleteMeetingUseCase } from '../application/usecases/meeting/DeleteMeetingUseCase';
import { ENROLLMENT_SYMBOLS } from '../domain/symbols/Enrollment';
import { EnrollmentRepositoryImpl } from '../infrastructure/api/EnrollmentRepositoryImpl';
import { EnrollmentService } from '../domain/services/EnrollmentService';
import { CreateEnrollmentUseCase } from '../application/usecases/enrollment/CreateEnrollmentUseCase';
import { ListEnrollmentsUseCase } from '../application/usecases/enrollment/ListEnrollmentsUseCase';
import { UpdateEnrollmentUseCase } from '../application/usecases/enrollment/UpdateEnrollmentUseCase';
import { DeleteEnrollmentUseCase } from '../application/usecases/enrollment/DeleteEnrollmentUseCase';
import { GRADING_SYMBOLS } from '../domain/symbols/Grading';
import { GradingRepositoryImpl } from '../infrastructure/api/GradingRepositoryImpl';
import { GradingService } from '../domain/services/GradingService';
import { GetFinalGradeUseCase } from '../application/usecases/grading/GetFinalGradeUseCase';
import { ACADEMIC_HISTORY_SYMBOLS } from '../domain/symbols/AcademicHistory';
import { AcademicHistoryRepositoryImpl } from '../infrastructure/api/AcademicHistoryRepositoryImpl';
import { AcademicHistoryService } from '../domain/services/AcademicHistoryService';
import { GetAcademicHistoryUseCase } from '../application/usecases/academic-history/GetAcademicHistoryUseCase';

export const container = new Container();
container.bind(TEACHER_SYMBOLS.REPOSITORY).to(TeacherRepositoryImpl);
container.bind(TEACHER_SYMBOLS.SERVICE).to(TeacherService);
container.bind(TEACHER_SYMBOLS.CREATE_USE_CASE).to(CreateTeacherUseCase);
container.bind(TEACHER_SYMBOLS.LIST_USE_CASE).to(ListTeachersUseCase);
container.bind(TEACHER_SYMBOLS.GET_USE_CASE).to(GetTeacherUseCase);
container.bind(TEACHER_SYMBOLS.UPDATE_USE_CASE).to(UpdateTeacherUseCase);
container.bind(TEACHER_SYMBOLS.DELETE_USE_CASE).to(DeleteTeacherUseCase);

container.bind(REPORT_CARD_SYMBOLS.REPOSITORY).to(ReportCardRepositoryImpl);
container.bind(REPORT_CARD_SYMBOLS.SERVICE).to(ReportCardService);
container.bind(REPORT_CARD_SYMBOLS.GET_USE_CASE).to(GetReportCardUseCase);

container.bind(OFFICIAL_RECORD_SYMBOLS.REPOSITORY).to(OfficialRecordRepositoryImpl);
container.bind(OFFICIAL_RECORD_SYMBOLS.SERVICE).to(OfficialRecordService);
container.bind(OFFICIAL_RECORD_SYMBOLS.GET_USE_CASE).to(GetOfficialRecordUseCase);

container.bind(STATISTICS_SYMBOLS.REPOSITORY).to(StatisticsRepositoryImpl);
container.bind(STATISTICS_SYMBOLS.SERVICE).to(StatisticsService);
container.bind(STATISTICS_SYMBOLS.ATTENDANCE_USE_CASE).to(GetAttendanceStatisticsUseCase);
container.bind(STATISTICS_SYMBOLS.PERFORMANCE_USE_CASE).to(GetPerformanceStatisticsUseCase);

container.bind(EXPORT_SYMBOLS.REPOSITORY).to(ExportRepositoryImpl);
container.bind(EXPORT_SYMBOLS.SERVICE).to(ExportService);
container.bind(EXPORT_SYMBOLS.REPORT_CARD_USE_CASE).to(ExportReportCardUseCase);
container.bind(EXPORT_SYMBOLS.STATISTICS_USE_CASE).to(ExportStatisticsUseCase);

container.bind(PROMOTION_SYMBOLS.REPOSITORY).to(PromotionRepositoryImpl);
container.bind(PROMOTION_SYMBOLS.SERVICE).to(PromotionService);
container.bind(PROMOTION_SYMBOLS.USE_CASE).to(PromoteStudentUseCase);

container.bind(PROMOTION_ACT_SYMBOLS.REPOSITORY).to(PromotionActRepositoryImpl);
container.bind(PROMOTION_ACT_SYMBOLS.SERVICE).to(PromotionActService);
container.bind(PROMOTION_ACT_SYMBOLS.CREATE_USE_CASE).to(CreatePromotionActUseCase);
container.bind(PROMOTION_ACT_SYMBOLS.GET_USE_CASE).to(GetPromotionActUseCase);
container.bind(PROMOTION_ACT_SYMBOLS.LIST_USE_CASE).to(ListPromotionActsUseCase);
container.bind(PROMOTION_ACT_SYMBOLS.DELETE_USE_CASE).to(DeletePromotionActUseCase);

container.bind(TEACHER_ASSIGNMENT_SYMBOLS.REPOSITORY).to(TeacherAssignmentRepositoryImpl);
container.bind(TEACHER_ASSIGNMENT_SYMBOLS.SERVICE).to(TeacherAssignmentService);
container.bind(TEACHER_ASSIGNMENT_SYMBOLS.CREATE_USE_CASE).to(CreateTeacherAssignmentUseCase);
container.bind(TEACHER_ASSIGNMENT_SYMBOLS.GET_USE_CASE).to(GetTeacherAssignmentUseCase);
container.bind(TEACHER_ASSIGNMENT_SYMBOLS.LIST_USE_CASE).to(ListTeacherAssignmentsUseCase);

container.bind(TEACHER_PLANNING_SYMBOLS.REPOSITORY).to(TeacherPlanningRepositoryImpl);
container.bind(TEACHER_PLANNING_SYMBOLS.SERVICE).to(TeacherPlanningService);
container.bind(TEACHER_PLANNING_SYMBOLS.CREATE_USE_CASE).to(CreateTeacherPlanningUseCase);
container.bind(TEACHER_PLANNING_SYMBOLS.GET_USE_CASE).to(GetTeacherPlanningUseCase);
container.bind(TEACHER_PLANNING_SYMBOLS.LIST_USE_CASE).to(ListTeacherPlanningsUseCase);

container.bind(STUDENT_SYMBOLS.REPOSITORY).to(StudentRepositoryImpl);
container.bind(STUDENT_SYMBOLS.SERVICE).to(StudentService);
container.bind(STUDENT_SYMBOLS.CREATE_USE_CASE).to(CreateStudentUseCase);
container.bind(STUDENT_SYMBOLS.LIST_USE_CASE).to(ListStudentsUseCase);
container.bind(STUDENT_SYMBOLS.GET_USE_CASE).to(GetStudentUseCase);
container.bind(STUDENT_SYMBOLS.UPDATE_USE_CASE).to(UpdateStudentUseCase);
container.bind(STUDENT_SYMBOLS.DELETE_USE_CASE).to(DeleteStudentUseCase);

container.bind(REPRESENTATIVE_SYMBOLS.REPOSITORY).to(RepresentativeRepositoryImpl);
container.bind(REPRESENTATIVE_SYMBOLS.SERVICE).to(RepresentativeService);
container.bind(REPRESENTATIVE_SYMBOLS.CREATE_USE_CASE).to(CreateRepresentativeUseCase);
container.bind(REPRESENTATIVE_SYMBOLS.LIST_USE_CASE).to(ListRepresentativesUseCase);
container.bind(REPRESENTATIVE_SYMBOLS.GET_USE_CASE).to(GetRepresentativeUseCase);
container.bind(REPRESENTATIVE_SYMBOLS.UPDATE_USE_CASE).to(UpdateRepresentativeUseCase);
container.bind(REPRESENTATIVE_SYMBOLS.DELETE_USE_CASE).to(DeleteRepresentativeUseCase);

container.bind(ASSESSMENT_SYMBOLS.REPOSITORY).to(AssessmentRepositoryImpl);
container.bind(ASSESSMENT_SYMBOLS.SERVICE).to(AssessmentService);
container.bind(ASSESSMENT_SYMBOLS.CREATE_USE_CASE).to(CreateAssessmentUseCase);
container.bind(ASSESSMENT_SYMBOLS.LIST_USE_CASE).to(ListAssessmentsUseCase);
container.bind(ASSESSMENT_SYMBOLS.UPDATE_USE_CASE).to(UpdateAssessmentUseCase);
container.bind(ASSESSMENT_SYMBOLS.DELETE_USE_CASE).to(DeleteAssessmentUseCase);

container.bind(ATTENDANCE_SYMBOLS.REPOSITORY).to(AttendanceRepositoryImpl);
container.bind(ATTENDANCE_SYMBOLS.SERVICE).to(AttendanceService);
container.bind(ATTENDANCE_SYMBOLS.CREATE_USE_CASE).to(CreateAttendanceUseCase);
container.bind(ATTENDANCE_SYMBOLS.LIST_USE_CASE).to(ListAttendanceUseCase);
container.bind(ATTENDANCE_SYMBOLS.UPDATE_USE_CASE).to(UpdateAttendanceUseCase);
container.bind(ATTENDANCE_SYMBOLS.DELETE_USE_CASE).to(DeleteAttendanceUseCase);

container.bind(BEHAVIOR_REPORT_SYMBOLS.REPOSITORY).to(BehaviorReportRepositoryImpl);
container.bind(BEHAVIOR_REPORT_SYMBOLS.SERVICE).to(BehaviorReportService);
container.bind(BEHAVIOR_REPORT_SYMBOLS.CREATE_USE_CASE).to(CreateBehaviorReportUseCase);
container.bind(BEHAVIOR_REPORT_SYMBOLS.LIST_USE_CASE).to(ListBehaviorReportsUseCase);
container.bind(BEHAVIOR_REPORT_SYMBOLS.UPDATE_USE_CASE).to(UpdateBehaviorReportUseCase);
container.bind(BEHAVIOR_REPORT_SYMBOLS.DELETE_USE_CASE).to(DeleteBehaviorReportUseCase);

container.bind(MEETING_SYMBOLS.REPOSITORY).to(MeetingRepositoryImpl);
container.bind(MEETING_SYMBOLS.SERVICE).to(MeetingService);
container.bind(MEETING_SYMBOLS.CREATE_USE_CASE).to(CreateMeetingUseCase);
container.bind(MEETING_SYMBOLS.LIST_USE_CASE).to(ListMeetingsUseCase);
container.bind(MEETING_SYMBOLS.UPDATE_USE_CASE).to(UpdateMeetingUseCase);
container.bind(MEETING_SYMBOLS.DELETE_USE_CASE).to(DeleteMeetingUseCase);

container.bind(ENROLLMENT_SYMBOLS.REPOSITORY).to(EnrollmentRepositoryImpl);
container.bind(ENROLLMENT_SYMBOLS.SERVICE).to(EnrollmentService);
container.bind(ENROLLMENT_SYMBOLS.CREATE_USE_CASE).to(CreateEnrollmentUseCase);
container.bind(ENROLLMENT_SYMBOLS.LIST_USE_CASE).to(ListEnrollmentsUseCase);
container.bind(ENROLLMENT_SYMBOLS.UPDATE_USE_CASE).to(UpdateEnrollmentUseCase);
container.bind(ENROLLMENT_SYMBOLS.DELETE_USE_CASE).to(DeleteEnrollmentUseCase);

container.bind(GRADING_SYMBOLS.REPOSITORY).to(GradingRepositoryImpl);
container.bind(GRADING_SYMBOLS.SERVICE).to(GradingService);
container.bind(GRADING_SYMBOLS.FINAL_USE_CASE).to(GetFinalGradeUseCase);

container.bind(ACADEMIC_HISTORY_SYMBOLS.REPOSITORY).to(AcademicHistoryRepositoryImpl);
container.bind(ACADEMIC_HISTORY_SYMBOLS.SERVICE).to(AcademicHistoryService);
container.bind(ACADEMIC_HISTORY_SYMBOLS.GET_USE_CASE).to(GetAcademicHistoryUseCase);
